/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import richTextBlocksExtended from "@crispyyv/strapi-plugin-rich-text-blocks-extended/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "rich-text-blocks-extended": richTextBlocksExtended,
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
  },
});
